import type { Document, Workspace } from "./model";
const now = "2026-09-09T06:00:00.000Z";
const paper = (
  id: string,
  title: string,
  summary: string,
  year: string,
  tags: string[],
  status: Document["status"],
  markdown: string,
  url: string,
): Document => ({
  id,
  title,
  summary,
  year,
  tags,
  status,
  markdown,
  url,
  kind: "paper",
  blocks: null,
  folder: "",
  favorite: id === "blip2",
  relatedIds: [],
  deletedAt: null,
  updatedAt: now,
  createdAt: now,
  revision: 1,
});
export function demoWorkspace(): Workspace {
  return {
    documents: [
      paper(
        "clip",
        "CLIP",
        "用自然语言监督，连接图像与文本的表示空间。",
        "2021",
        ["VLM", "对比学习"],
        "read",
        "## 一句话理解\n\n通过图像与文本的对比学习，把两种模态映射到同一个表示空间。\n\n## 核心思路\n\n- 图像编码器与文本编码器分别生成特征。\n- 拉近匹配的图文对，拉远不匹配的图文对。\n- 用自然语言描述类别，实现零样本分类。\n\n## 核心代码\n\n```python\nimport torch.nn.functional as F\n\ndef clip_logits(image_features, text_features, logit_scale):\n    image_features = F.normalize(image_features, dim=-1)\n    text_features = F.normalize(text_features, dim=-1)\n    return logit_scale.exp() * image_features @ text_features.T\n```\n\n## 我的思考\n\n表示对齐如何帮助下游任务？继续阅读时重点关注训练目标的变化。",
        "https://arxiv.org/abs/2103.00020",
      ),
      paper(
        "blip",
        "BLIP",
        "统一理解与生成，用自举方式改善图文训练数据。",
        "2022",
        ["VLM", "预训练"],
        "read",
        "## 核心问题\n\n网络图文数据存在噪声，如何同时支持视觉语言理解与生成？\n\n## 方法笔记\n\n- 图像文本对比学习（ITC）\n- 图像文本匹配（ITM）\n- 语言建模（LM）\n\n## 待补充\n\n记录 Captioning 与 Filtering 的具体流程。",
        "https://arxiv.org/abs/2201.12086",
      ),
      paper(
        "blip2",
        "BLIP-2",
        "冻结视觉编码器与大语言模型，用 Q-Former 连接两者。",
        "2023",
        ["VLM", "Q-Former"],
        "reading",
        "## 一句话理解\n\n用一个轻量的 Q-Former，让冻结的视觉编码器与大语言模型建立连接。\n\n## 核心模块 · Q-Former\n\n一组可学习的 query 从图像特征中提取与语言相关的信息，再映射到语言模型的输入空间。\n\n### 两阶段训练\n\n1. 视觉语言表示学习：连接冻结的图像编码器。\n2. 视觉到语言生成学习：连接冻结的大语言模型。\n\n## 核心代码\n\n```python\n# 示意代码：观察输入与输出的维度\n# queries: [batch, num_queries, hidden_dim]\n# image_tokens: [batch, num_patches, vision_dim]\nquery_output = q_former(\n    query_embeds=queries,\n    encoder_hidden_states=image_tokens,\n)\nlanguage_inputs = projection(query_output.last_hidden_state)\n```\n\n## 还想弄清楚\n\n- Query 的数量对信息提取有什么影响？\n- 两阶段训练分别更新哪些参数？\n\n> 这里是演示笔记。正式数据库会从空白开始，你可以建立自己的理解。",
        "https://arxiv.org/abs/2301.12597",
      ),
      paper(
        "instructblip",
        "InstructBLIP",
        "将指令引入视觉特征提取，探索通用视觉语言能力。",
        "2023",
        ["VLM", "指令微调"],
        "unread",
        "## 阅读目标\n\n关注 instruction-aware Q-Former 与 BLIP-2 的区别。",
        "https://arxiv.org/abs/2305.06500",
      ),
      paper(
        "siglip",
        "SigLIP",
        "从损失函数出发，重新思考图像与文本的对齐。",
        "2023",
        ["VLM", "对比学习"],
        "unread",
        "## 阅读目标\n\n比较 sigmoid loss 与 CLIP 使用的 softmax loss。",
        "https://arxiv.org/abs/2303.15343",
      ),
      {
        ...paper(
          "pytorch",
          "PyTorch · 张量与维度",
          "从 shape 开始，理解模型中的数据流动。",
          "",
          ["PyTorch", "基础"],
          "reading",
          "## 先看维度，再看计算\n\n阅读模型代码时，为每一步标注张量形状，能够更快理解模块之间的关系。\n\n```python\nimport torch\n\nx = torch.randn(2, 16, 768)\n# batch × tokens × hidden\ny = x.transpose(1, 2)\nprint(y.shape)  # torch.Size([2, 768, 16])\n```\n\n## 易混淆的操作\n\n- view：要求内存布局兼容。\n- reshape：必要时可能复制数据。\n- permute：调整维度顺序。",
          "",
        ),
        kind: "note",
        folder: "编程与工具/PyTorch",
        favorite: true,
        relatedIds: ["blip2"],
      },
      {
        ...paper(
          "music",
          "音乐 · 从大调音阶开始",
          "用耳朵认识音程，用练习建立感觉。",
          "",
          ["音乐", "乐理"],
          "reading",
          "## 大调音阶\n\n全 · 全 · 半 · 全 · 全 · 全 · 半\n\n## 本周练习\n\n- 唱出 C 大调音阶。\n- 听辨大三度与纯五度。\n- 记录一个喜欢的和弦进行。",
          "",
        ),
        kind: "note",
        folder: "兴趣爱好/音乐",
      },
    ],
    routes: [
      {
        id: "vlm",
        title: "视觉语言模型",
        description: "从图文对齐到多模态理解，沿着问题的演变慢慢读。",
        revision: 1,
        updatedAt: now,
        nodes: [
          { id: "n1", paperId: "clip", position: { x: 40, y: 160 } },
          { id: "n2", paperId: "blip", position: { x: 350, y: 60 } },
          { id: "n3", paperId: "blip2", position: { x: 660, y: 60 } },
          { id: "n4", paperId: "instructblip", position: { x: 970, y: 60 } },
          { id: "n5", paperId: "siglip", position: { x: 350, y: 320 } },
        ],
        edges: [
          { id: "e1", source: "n1", target: "n2", label: "关联阅读 · 理解与生成" },
          { id: "e2", source: "n2", target: "n3", label: "连接冻结的大模型" },
          { id: "e3", source: "n3", target: "n4", label: "指令感知" },
          { id: "e4", source: "n1", target: "n5", label: "探索对齐损失" },
        ],
      },
    ],
    folders: ["编程与工具/PyTorch", "基础知识/深度学习", "兴趣爱好/音乐"],
  };
}
